In [33]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso,ElasticNet,Ridge,LinearRegression
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV,KFold
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_csv("C:\\Users\\Aravinthan\\Desktop\\MLO\\data\\Boston.CSV")

In [3]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio   black  lstat  medv
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33  36.2

In [4]:
x = data.iloc[:,:12]
y = data.iloc[:,12]

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [6]:
params = {"alpha":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]}

In [7]:
model = Lasso()

In [9]:
cval = KFold(n_splits=10)

In [10]:
gsearch = GridSearchCV(model,param_grid=params,cv=cval)

In [11]:
result = gsearch.fit(x_train,y_train)

In [12]:
result.best_params_

{'alpha': 0.1}

In [13]:
rsearch = RandomizedSearchCV(model,param_distributions=params,cv=cval)

In [14]:
result2 = rsearch.fit(x_train,y_train)

In [15]:
result2.best_params_

{'alpha': 0.1}

In [16]:
best_model = Lasso(alpha=0.1)

In [17]:
best_model.fit(x_train,y_train)

Lasso(alpha=0.1)

In [18]:
best_model.coef_

array([-0.11328068,  0.04781981, -0.03820164, -0.        ,  3.61884406,
       -0.01418714, -1.11799589,  0.21463545, -0.01329635, -0.90308334,
        0.00934528, -0.52609513])

In [19]:
predict = best_model.predict(x_test)

In [20]:
print(np.sqrt(mean_squared_error(y_test,predict)))

6.027323441426988


In [22]:
model2 = ElasticNet(alpha=0.1)

In [23]:
model2.fit(x_train,y_train)

ElasticNet(alpha=0.1)

In [24]:
model2.coef_

array([-0.11375969,  0.05072252, -0.04706097, -0.        ,  3.15789825,
       -0.0116611 , -1.14763402,  0.22804594, -0.01371831, -0.92198436,
        0.00902839, -0.55617033])

In [25]:
predict2 = model2.predict(x_test)

In [26]:
print(np.sqrt(mean_squared_error(y_test,predict2)))

6.043920518774257


In [28]:
model3 = Ridge(alpha=0.1)

In [29]:
model3.fit(x_train,y_train)

Ridge(alpha=0.1)

In [30]:
model3.coef_

array([-1.24679448e-01,  4.50563888e-02,  1.49700658e-02, -1.49647500e+01,
        3.78424875e+00, -3.43239061e-03, -1.38739229e+00,  2.62796984e-01,
       -1.22553465e-02, -1.06296417e+00,  8.79885251e-03, -4.95292108e-01])

In [31]:
predict3 = model3.predict(x_test)

In [32]:
print(np.sqrt(mean_squared_error(y_test,predict3)))

5.855811948780432
